services:
  whisper:
    build:
      context: .
      dockerfile: docker/whisper.Dockerfile
    ports:
      - "7600:7600"
    volumes:
      - ./docker/models:/models:ro
    restart: unless-stopped

  piper:
    build:
      context: .
      dockerfile: docker/piper.Dockerfile
    ports:
      - "7602:7602"
    volumes:
      - ./docker/models:/models:ro
    restart: unless-stopped
